spring:
  application:
    name: vending-inventory-system

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/vending_inventory?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: false

  security:
    user:
      name: admin
      password: admin123

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    com.vending: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Application Properties
app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-expiration-ms: 604800000 # 7 days in milliseconds

  security:
    max-failed-login-attempts: 5
    account-lockout-duration-minutes: 30
    rate-limit:
      login-requests-per-minute: 10  # Max 10 login attempts per minute per IP
      login-requests-window-seconds: 60  # 1 minute window

  inventory:
    low-stock-threshold: 0.20 # 20%
    reorder-threshold: 0.15 # 15%

  tax:
    hst-rate: 0.13 # Ontario HST rate

  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  email:
    enabled: ${EMAIL_ENABLED:false}  # Disabled by default, enable in production
    from: ${EMAIL_FROM:noreply@vendingsystem.com}
    from-name: ${EMAIL_FROM_NAME:Vending Inventory System}
    report:
      enabled: ${EMAIL_REPORTS_ENABLED:false}
      default-recipient: ${EMAIL_DEFAULT_RECIPIENT:admin@example.com}
      recipients: ${EMAIL_RECIPIENTS:}  # Comma-separated list
      daily-cron: "0 0 8 * * *"  # 8 AM daily
      weekly-cron: "0 0 8 * * MON"  # 8 AM Monday
      monthly-cron: "0 0 8 1 * *"  # 8 AM 1st of month

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
